
/**
 * Representation of hypotrochoid.
 * 
 * Hypotrochoid - roulette, described with point on surface of satellite circle inside main circle.
 * */
class Hypocycloid {

  static #buffer = {
    matrix: [[0,0]]
  }

  /**
   * Returns value of x-axis of hypocycloid by angle, radius of center circle and radius of satellite circle.
   * @param {number} [angle] Angle of hypocycloid.
   * @param {number} [centerR] Radius of center circle.
   * @param {number} [satelliteR] Radius of satellite circle.
   * @returns Number
   * */
  static x(angle: number, centerR: number = 1, satelliteR: number = 1): number{
    let R = centerR - satelliteR;
    return R * Math.cos(angle) + satelliteR * Math.cos(R / satelliteR * angle)
  }


  /**
   * Returns value of y-axis of hypocycloid by angle, radius of center circle and radius of satellite circle.
   * @param {number} [angle] Angle of hypocycloid.
   * @param {number} [centerR] Radius of center circle.
   * @param {number} [satelliteR] Radius of satellite circle.
   * @returns {number} Number
   * */
   static y(angle: number, centerR: number = 1, satelliteR: number = 1): number {
    let R = centerR - satelliteR;
    return R * Math.sin(angle) - satelliteR * Math.sin(R / satelliteR * angle)
  }




  /**
   * Returns matrix with points, generated by nex parameters.
   * @param {number} [start] Start angle.
   * @param {number} [centerR] Radius of main circle.
   * @param {number} [satelliteR] Radius of satellite circle.
   * @param {number} [length] Duration of rotation in radians.
   * @param {number} [step] Step of rotation in radians,
   * @returns {matrix} [ [ x: number , y: number ] , ... ]
   * */
  static generate(start: number = 0, centerR: number=1,satelliteR: number=1,length: number=Math.TAU,step: number=Math.TAU * .001) :matrix {
    let matrix = []
    for(let i = start; i < start + length; i+=step){ matrix.push([ this.x(i , centerR , satelliteR) , this.y(i , centerR , satelliteR) ]) }
    return matrix
  }

  static get last() :matrix { return this.#buffer.matrix }
}

export default Hypocycloid